### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by oskov** [oskov/rtu-algoritmi-2#4]
Web lietotne satur tikai statiskus elementus kas apraksta

- [x] izvēlētas saspiešanas metodes 1p
pētījuma rezultātus
- [x]  apskatu tekstā formā 1p

- [x] diagrammas 1p

- [x] Web lietotne satur interaktīvus elementus, kas atļauj mainīt lapas izskatu (piemēram, datus, kas tiek attēloti diagrammās) (4 punkti)

- [x] Web lietotne atļauj saspiest failu izmantojot izvēlēto metodi (2 punkti)

- [x] attēlo informāciju par faila saspiešanas pakāpi (1 punkts)

Progress:
 10/ 10

**Comment by Markvarte** [comment]
Ёёёлки, чё так много..

**Comment by BreakingSoul** [comment]
gg ez
